-- Seed data: 34 members of UEEMT-Tokat
INSERT INTO members (prenom, nom, statut, filiere, universite, niveau, is_validated, cotisation_payee) VALUES
('Abdoul Karim', 'FASKOYE', 'Étudiant', 'Informatique', 'Tokat Gaziosmanpaşa Üniversitesi', '4ème année', true, true),
('Steeve Donald', 'Compaoré', 'Étudiant', 'Bilgisayar Mühendisliği', 'Tokat Gaziosmanpaşa Üniversitesi', '3ème année', true, true),
('Fanta', 'Traoré', 'Étudiant', 'Médecine', 'Tokat Gaziosmanpaşa Üniversitesi', '2ème année', true, true),
('Ibrahim', 'Konaré', 'Étudiant', 'Économie', 'Tokat Gaziosmanpaşa Üniversitesi', '3ème année', true, true),
('Aminata', 'Diallo', 'Étudiant', 'Pharmacie', 'Tokat Gaziosmanpaşa Üniversitesi', '1ère année', true, false),
('Moussa', 'Coulibaly', 'Étudiant', 'Génie Civil', 'Tokat Gaziosmanpaşa Üniversitesi', '2ème année', true, true),
('Fatoumata', 'Sidibé', 'Étudiant', 'Biologie', 'Tokat Gaziosmanpaşa Üniversitesi', '3ème année', false, false),
('Seydou', 'Camara', 'Étudiant', 'Mécanique', 'Tokat Gaziosmanpaşa Üniversitesi', '4ème année', true, true),
('Mariam', 'Kéïta', 'Étudiant', 'Chimie', 'Tokat Gaziosmanpaşa Üniversitesi', '2ème année', true, false),
('Oumar', 'Sanogo', 'Étudiant', 'Électronique', 'Tokat Gaziosmanpaşa Üniversitesi', '3ème année', true, true),
('Kadiatou', 'Maïga', 'Étudiant', 'Tourisme', 'Tokat Gaziosmanpaşa Üniversitesi', '1ère année', false, false),
('Adama', 'Traoré', 'Étudiant', 'Informatique', 'Tokat Gaziosmanpaşa Üniversitesi', '2ème année', true, true),
('Bintou', 'Dembélé', 'Étudiant', 'Agronomie', 'Tokat Gaziosmanpaşa Üniversitesi', '3ème année', true, false),
('Hamidou', 'Touré', 'Étudiant', 'Médecine', 'Tokat Gaziosmanpaşa Üniversitesi', '4ème année', true, true),
('Rokia', 'Doumbia', 'Étudiant', 'Économie', 'Tokat Gaziosmanpaşa Üniversitesi', '1ère année', false, false),
('Lassana', 'Diarra', 'Étudiant', 'Génie Civil', 'Tokat Gaziosmanpaşa Üniversitesi', '2ème année', true, true),
('Hawa', 'Sissoko', 'Étudiant', 'Pharmacie', 'Tokat Gaziosmanpaşa Üniversitesi', '3ème année', true, true),
('Bakary', 'Kouyaté', 'Étudiant', 'Biologie', 'Tokat Gaziosmanpaşa Üniversitesi', '1ère année', true, false),
('Safiatou', 'N'Diaye', 'Étudiant', 'Chimie', 'Tokat Gaziosmanpaşa Üniversitesi', '2ème année', false, false),
('Drissa', 'Coulibaly', 'Étudiant', 'Mécanique', 'Tokat Gaziosmanpaşa Üniversitesi', '4ème année', true, true),
('Aissata', 'Barry', 'Étudiant', 'Électronique', 'Tokat Gaziosmanpaşa Üniversitesi', '3ème année', true, false),
('Cheick Oumar', 'Diallo', 'Étudiant', 'Informatique', 'Tokat Gaziosmanpaşa Üniversitesi', '2ème année', true, true),
('Tenin', 'Coulibaly', 'Étudiant', 'Médecine', 'Tokat Gaziosmanpaşa Üniversitesi', '1ère année', false, false),
('Modibo', 'Keïta', 'Étudiant', 'Agronomie', 'Tokat Gaziosmanpaşa Üniversitesi', '3ème année', true, true),
('Djeneba', 'Fofana', 'Étudiant', 'Économie', 'Tokat Gaziosmanpaşa Üniversitesi', '2ème année', true, false),
('Yacouba', 'Traoré', 'Étudiant', 'Tourisme', 'Tokat Gaziosmanpaşa Üniversitesi', '4ème année', true, true),
('Maimouna', 'Sanogo', 'Élève lycée', NULL, 'Lycée de Tokat', 'Terminale', false, false),
('Souleymane', 'Diakité', 'Élève lycée', NULL, 'Lycée de Tokat', '2nde', true, true),
('Kadija', 'Koné', 'Élève lycée', NULL, 'Lycée de Tokat', '1ère', false, false),
('Abdoulaye', 'Koné', 'Étudiant', 'Génie Civil', 'Tokat Gaziosmanpaşa Üniversitesi', '2ème année', true, true),
('Awa', 'Diarra', 'Étudiant', 'Biologie', 'Tokat Gaziosmanpaşa Üniversitesi', '1ère année', false, false),
('Idrissa', 'Camara', 'Étudiant', 'Pharmacie', 'Tokat Gaziosmanpaşa Üniversitesi', '3ème année', true, false),
('Oumou', 'Sissoko', 'Étudiant', 'Chimie', 'Tokat Gaziosmanpaşa Üniversitesi', '2ème année', true, true),
('Boubacar', 'Maïga', 'Mezun', 'Informatique', 'Tokat Gaziosmanpaşa Üniversitesi', 'Diplômé', true, true);
